raw_path: data/raw/
preprocessed_path: data/preprocessed/
segmented_path: data/segmented/
artifacts_path: artifacts/
sampling_frequency: 50
window_size_sec: 4
window_slide_sec: 1
timestamp_col: SoftwareTimestamp
label_col: Label
sublabel: Sublabel
sensor_columns_raw:
  - Accelerometer/Raw.X
  - Accelerometer/Raw.Y
  - Accelerometer/Raw.Z
  - Gyroscope/Raw.X
  - Gyroscope/Raw.Y
  - Gyroscope/Raw.Z
sensor_columns_model:
  - Accelerometer/Raw.X
  - Accelerometer/Raw.Y
  - Accelerometer/Raw.Z
  - Accelerometer/Magnitude
  - Gyroscope/Raw.X
  - Gyroscope/Raw.Y
  - Gyroscope/Raw.Z
  - Gyroscope/Magnitude
f_high_cutoff: 3
first_model_labels: ["walking", "running", "upright-still", "laying"]